functional:
  - Должна быть возможность перехода в форму регистрации нового пользователя 1  
  - Должна быть возможность перехода в форму авторизации пользователя 2
  - Должна быть возможность выбора русского или английского языка отображения текста 3
  - Для неавторизованного пользователя должна быть возможность пробной игры с ботом, подобранной наугад 4
  - Авторизованный пользователь может выбрать определенную игру, иначе она будет подобрана наугад 5
  - Авторизованный пользователь может выбрать игру по уровню сложности 6
  - Авторизованный пользователь может выбрать игру с ботом, другим авторизованным пользователем или другом (игра будет доступна по ссылке) 7
  - Другой авторизованный пользователь может следить за ходом игры 8
  - Авторизованный пользователь получает очки, на основе которых строится рейтинг за неделю, месяц и за все время 9
  - Оба игрока могут менять язык программирования в процессе игры 10
  - Оба игрока видят друг у друга редактор с кодом 11
  - Оба игрока видят вывод кода друг у друга в режиме реального времени 12
  - Выигрывает игрок, который быстрее решит задачу 13
  - Оба игрока видят таймер с обратным отсчетом игрового времени 14
  - В игре есть чат, в котором общаются зарегистрированные пользователи 15
  - Завершенная игра доступна в записи 16
non-functional:
  - Редактор для ввода кода выглядит как проигрыватель 17
  - Должна быть разработана веб-версия сайта в виде SPA без перезагрузки страницы 18
  - Сайт должен иметь адаптивную верстку при просмотре веб-страницы на компьютерах и на мобильных устройствах 19
  - Размеры кнопок, расположение элементов в формах и дизайн должны сохраняться при переключении  языка текста с русского на английский 20
  - Сайт должен содержать шапку с формой регистрации, формой авторизации и кнопкой перехода к пробной игре 21
  - Сайт должен быть совместимым с последней, на момент тестирования, версией браузера Google Chrome, Firefox и Explorer 22
implicit:
  - При отсутствии соединения с сетью интернет должно отображаться стандартное текстовое сообщение браузера об отсутствии подключения 23
  - При низкой скорости подключения (3G, 4G) страница должна в первую очередь отображать текст, затем настройки стилей, затем изображения 24
  - Протокол передачи данных HTTP должен поддерживать расширения шифрования SSL TLS 25
  - Должен быть реализован механизм управления сессиями Cookies 26
  - В сессии браузера должна храниться информация о рейтинге и данные учетной записи пользователя 27
  - Поля авторизации, регистрации и выбора цены товара в каталоге должны валидировать данные, вводимые пользователем 28
