functional:
  - Должна быть возможность регистрации нового пользователя 1  
  - Должна быть возможность авторизации пользователя 2
  - Должна быть возможность выбора русского или английского языка отображения текста 3
  - Для неавторизованного пользователя должна быть возможность пробной игры с ботом, подобранной наугад 4
  - Авторизованный пользователь может выбрать определенную игру или выбрать игру наугад 5
  - Авторизованный пользователь может выбрать игру по уровню сложности 6
  - Авторизованный пользователь может выбрать игру с ботом, другим авторизованным пользователем или другом (по ссылке) 7
  - Другой авторизованный пользователь может следить за ходом игры 8
  - Авторизованный пользователь получает очки, на основе которых строится рейтинг за неделю, месяц и за все время 9
  - Оба игрока могут менять язык программирования в процессе игры 10
  - Оба игрока видят друг у друга редактор с кодом 11
  - Оба игрока видят вывод кода друг у друга в режиме реального времени 12
  - Выигрывает игрок, который быстрее решит задачу 13
  - Оба игрока видят таймер с обратным отсчетом игрового времени 14
  - В игре есть чат, в котором общаются зарегистрированные пользователи 15
  - Завершенная игра должна быть доступна в записи и редактор кода выглядеть как проигрыватель 16
non-functional:
  - Должна быть разработана веб-версия сайта в виде SPA без перезагрузки страницы 17
  - Сайт должен иметь адаптивную верстку при просмотре веб-страницы на компьютерах и на мобильных устройствах 18
  - Размеры кнопок, расположение элементов в формах и дизайн должны сохраняться при переключении  языка текста с русского на английский 19
  - Сайт должен содержать шапку с формой регистрации, формой авторизации и кнопкой перехода к пробной игре 20
  - Основные элементы сайта должны соответствовать требованиям дизайна 21
  - Сайт должен быть совместимым с последней, на момент тестирования, версией браузера Google Chrome, Firefox и Explorer 22
implicit:
  - При отсутствии соединения с сетью интернет должно отображаться стандартное текстовое сообщение браузера об отсутствии подключения 23
  - Протокол передачи данных HTTP должен поддерживать расширения шифрования SSL TLS 24
  - Поля авторизации и регистрации должны валидировать данные, вводимые пользователем 25
